baseURL = ""
languageCode = "en-us"
theme = "raditian-free-hugo-theme"
[[menu.footer]]
URL = "html/terms.html"
name = "Terms & Conditions"
weight = 3
[[menu.footer]]
URL = "html/privacypolicy.html"
name = "Privacy Policy"
weight = 2
[[menu.footer]]
URL = "#about"
name = "About"
weight = 1
[[menu.header]]
URL = "#contact"
name = "Book In"
weight = 3
[[menu.header]]
URL = "#pricing"
name = "Pricing"
weight = 2
[[menu.header]]
URL = "#about"
name = "About"
weight = 1
[params]
googleTagManagerID = "GTM-000000"
[params.footer]
copyright = "© CDR - ChiropodyDrillRepairs. All rights reserved. CDR (ChiropodyDrillRepairs) is a subsidiary of TAFS Products LTD"
[params.footer.radity_logo]
_2x = "img/general/design-and-code-radity@2x.png"
alt = "Design & Code - Radity"
x = "img/general/design-and-code-radity.png"
[params.logo]
text1 = "CDR"
text2 = "ChiropodyDrillRepairs"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"
